# Generated by Django 3.0.6 on 2020-05-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsi_app', '0002_auto_20200525_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cites'},
        ),
    ]
