# Generated by Django 3.0.6 on 2020-06-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsi_app', '0006_advert_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertmessage',
            old_name='advert_id',
            new_name='advert',
        ),
        migrations.RenameField(
            model_name='advertmessage',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.DeleteModel(
            name='ObservedAds',
        ),
    ]
