# Generated by Django 3.0.6 on 2020-06-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsi_app', '0008_auto_20200621_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertMessage',
        ),
    ]
